# Default values for concept-publisher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
image:
  repository: coco/concept-publisher
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 1Gi
env:
  TOPIC: "" # This should be defined in the specific app-configs folder